opt_exp:
  batch_size: 32
  checkpoints_dir: ./checkpoints/e15_realgen_train
  continue_train: false
  data: rw_to_rw
  gpu_ids: &id001
  - '0'
  - '1'
  - '2'
  isTrain: false
  log_dir: ./logs/e15_realgen_train
  n_epochs: 50
  name: e15_realgen_train
  phase: rw_test
  results_dir: ./results/e15_realgen_train
  starting_epoch_count: best
opt_gen:
  base_model: resnet2_nblocks
  batch_size: 32
  beta1: 0.5
  checkpoints_load_dir: ./checkpoints/e15_realgen_train
  checkpoints_save_dir: ./checkpoints/e15_realgen_train
  continue_train: false
  gpu_ids:
  - '0'
  - '1'
  - '2'
  init_gain: 0.02
  init_type: xavier
  input_nc: 4
  isTrain: true
  lambda_L: 1
  lambda_cross: 1.0e-05
  lambda_reg: 0.001
  log_dir: ./logs/e15_realgen_train
  loss_type: L2_sumL2
  lr: 1.0e-05
  lr_decay_iters: 50
  lr_policy: lambda
  max_dataset_size: .inf
  n_epochs: 100
  name: rw_sims_gen
  net: G
  ngf: 64
  niter: 100
  niter_decay: 100
  no_dropout: false
  norm: instance
  num_threads: 4
  output_nc: 1
  parent_exp:
    batch_size: 32
    checkpoints_dir: ./checkpoints/e15_realgen_train
    continue_train: false
    data: rw_to_rw
    gpu_ids: *id001
    isTrain: false
    log_dir: ./logs/e15_realgen_train
    n_epochs: 50
    name: e15_realgen_train
    phase: rw_test
    results_dir: ./results/e15_realgen_train
    starting_epoch_count: best
  phase: rw_test
  resnet_blocks: 9
  results_dir: ./results/e15_realgen_train
  save_epoch_freq: 1
  save_latest_freq: 5000
  starting_epoch_count: best
  suffix: ''
  verbose: false
  weight_decay: 0.0001
