opt_decoder:
  base_model: resnet_decoder
  batch_size: 32
  beta1: 0.5
  checkpoints_load_dir: ./checkpoints/e19_real2dec_train
  checkpoints_save_dir: ./checkpoints/e19_real2dec_train
  continue_train: false
  encoder_res_blocks: 6
  gpu_ids:
  - '1'
  - '2'
  - '3'
  - '0'
  init_gain: 0.02
  init_type: xavier
  input_nc: 4
  isTrain: true
  lambda_L: 1
  lambda_cross: 1.0e-05
  lambda_reg: 0.0005
  log_dir: ./logs/e19_real2dec_train
  loss_type: L2_sumL1
  lr: 1.0e-05
  lr_decay_iters: 50
  lr_policy: step
  n_epochs: 50
  name: decoder
  net: G
  ngf: 64
  niter: 20
  niter_decay: 100
  no_dropout: false
  norm: instance
  num_threads: 4
  output_nc: 1
  parent_exp:
    batch_size: 32
    checkpoints_dir: ./checkpoints/e19_real2dec_train
    continue_train: false
    data: 1st_environment
    gpu_ids: &id001
    - '1'
    - '2'
    - '3'
    - '0'
    isFrozen: false
    isFrozen_gen: false
    isTrain: false
    isTrainGen: false
    isTrainLoc: false
    log_dir: ./logs/e19_real2dec_train
    n_epochs: 50
    name: e19_real2dec_train
    phase: rw_test_1env
    results_dir: ./results/e19_real2dec_train
    starting_epoch_count: best
  phase: rw_test_1env
  resnet_blocks: 9
  results_dir: ./results/e19_real2dec_train
  save_epoch_freq: 1
  save_latest_freq: 5000
  starting_epoch_count: best
  suffix: ''
  verbose: false
  weight_decay: 1.0e-05
opt_encoder:
  base_model: resnet_encoder
  batch_size: 32
  beta1: 0.5
  checkpoints_load_dir: ./checkpoints/e19_real2dec_train
  checkpoints_save_dir: ./checkpoints/e19_real2dec_train
  continue_train: false
  gpu_ids:
  - '1'
  - '2'
  - '3'
  - '0'
  init_gain: 0.02
  init_type: xavier
  input_nc: 4
  isTrain: true
  lambda_L: 1
  lambda_cross: 1.0e-05
  lambda_reg: 0.0005
  log_dir: ./logs/e19_real2dec_train
  loss_type: NoLoss
  lr: 1.0e-05
  lr_decay_iters: 50
  lr_policy: step
  max_dataset_size: .inf
  n_epochs: 50
  name: encoder
  net: G
  ngf: 64
  niter: 20
  niter_decay: 100
  no_dropout: false
  norm: instance
  num_threads: 4
  output_nc: 1
  parent_exp:
    batch_size: 32
    checkpoints_dir: ./checkpoints/e19_real2dec_train
    continue_train: false
    data: 1st_environment
    gpu_ids: *id001
    isFrozen: false
    isFrozen_gen: false
    isTrain: false
    isTrainGen: false
    isTrainLoc: false
    log_dir: ./logs/e19_real2dec_train
    n_epochs: 50
    name: e19_real2dec_train
    phase: rw_test_1env
    results_dir: ./results/e19_real2dec_train
    starting_epoch_count: best
  phase: rw_test_1env
  resnet_blocks: 6
  results_dir: ./results/e19_real2dec_train
  save_epoch_freq: 1
  save_latest_freq: 5000
  starting_epoch_count: best
  suffix: ''
  verbose: false
  weight_decay: 1.0e-05
opt_exp:
  batch_size: 32
  checkpoints_dir: ./checkpoints/e19_real2dec_train
  continue_train: false
  data: 1st_environment
  gpu_ids: *id001
  isFrozen: false
  isFrozen_gen: false
  isTrain: false
  isTrainGen: false
  isTrainLoc: false
  log_dir: ./logs/e19_real2dec_train
  n_epochs: 50
  name: e19_real2dec_train
  phase: rw_test_1env
  results_dir: ./results/e19_real2dec_train
  starting_epoch_count: best
opt_offset_decoder:
  base_model: resnet_decoder
  batch_size: 32
  beta1: 0.5
  checkpoints_load_dir: ./checkpoints/e19_real2dec_train
  checkpoints_save_dir: ./checkpoints/e19_real2dec_train
  continue_train: false
  encoder_res_blocks: 6
  gpu_ids:
  - '1'
  - '2'
  - '3'
  - '0'
  init_gain: 0.02
  init_type: xavier
  input_nc: 4
  isTrain: true
  lambda_L: 1
  lambda_cross: 0
  lambda_reg: 0
  log_dir: ./logs/e19_real2dec_train
  loss_type: L2_offset_loss
  lr: 1.0e-05
  lr_decay_iters: 50
  lr_policy: step
  n_epochs: 50
  name: offset_decoder
  net: G
  ngf: 64
  niter: 20
  niter_decay: 100
  no_dropout: false
  norm: instance
  num_threads: 4
  output_nc: 4
  parent_exp:
    batch_size: 32
    checkpoints_dir: ./checkpoints/e19_real2dec_train
    continue_train: false
    data: 1st_environment
    gpu_ids: *id001
    isFrozen: false
    isFrozen_gen: false
    isTrain: false
    isTrainGen: false
    isTrainLoc: false
    log_dir: ./logs/e19_real2dec_train
    n_epochs: 50
    name: e19_real2dec_train
    phase: rw_test_1env
    results_dir: ./results/e19_real2dec_train
    starting_epoch_count: best
  phase: rw_test_1env
  resnet_blocks: 12
  results_dir: ./results/e19_real2dec_train
  save_epoch_freq: 1
  save_latest_freq: 5000
  starting_epoch_count: best
  suffix: ''
  verbose: false
  weight_decay: 1.0e-05
